2024-05-27 15:00:41,961 heartattack  | pipeline.py:36 INFO     Configuration file loaded from config/default-config.yaml
2024-05-27 15:00:42,836 heartattack  | acquire_data.py:42 ERROR    An AWS error occurred: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
2024-05-27 15:00:42,837 heartattack  | acquire_data.py:83 ERROR    I/O error occurred while transferring data: s3://cloud-project-2/raw_data/Raw_Data_heart_attack_prediction_dataset.csv: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
